## Calculate the propogation matrix for the situations which need it

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import importlib
import xarray as xr
import os.path
import courtney
import scipy.optimize, scipy.signal
import cftime
import datetime
import scipy.linalg

import jemma_ODE_solvers3 as jde
import CAFE_tools2 as jcafe

<module 'jemma_ODE_solvers3' from '/Users/jjeff122/Documents/CLEX Undergraduate Scholarship/CLEX_project/jemma_ODE_solvers3.py'>

In [2]:
indices = xr.load_dataset('saved_indices.nc')

In [3]:
indices

<xarray.Dataset>
Dimensions:          (ensemble_member: 97, time: 720)
Coordinates:
    ensemble         int32 96
    month            (time) int64 1 2 3 4 5 6 7 8 9 10 ... 4 5 6 7 8 9 10 11 12
  * time             (time) object 1960-01-16 12:00:00 ... 2019-12-16 12:00:00
  * ensemble_member  (ensemble_member) int64 0 1 2 3 4 5 6 ... 91 92 93 94 95 96
Data variables:
    nino34_sst       (ensemble_member, time) float64 -3.346 -3.315 ... 1.608
    nino3_sst        (ensemble_member, time) float64 -3.226 -2.937 ... 1.299
    wholeP_i20       (ensemble_member, time) float64 -15.02 -11.01 ... 3.015
    westP_i20        (ensemble_member, time) float64 -0.8691 4.149 ... -2.495

## Parameter fit for the whole period with various spacial changes

In [4]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20',
                                 sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                        ensemble = range(97))

CPU times: user 10.1 s, sys: 127 ms, total: 10.3 s
Wall time: 5.53 s


(array([[[[-0.06466776,  0.02177951],
          [-1.11719283, -0.0060732 ]],
 
         [[-0.08231242,  0.02444426],
          [-1.11596024, -0.01767326]],
 
         [[-0.09559581,  0.02752041],
          [-1.36383916, -0.00656532]],
 
         [[-0.08769665,  0.0204296 ],
          [-1.29603549, -0.01935281]],
 
         [[-0.07635309,  0.02258171],
          [-1.17598214, -0.02529104]],
 
         [[-0.07436487,  0.02370763],
          [-1.09460535, -0.01619057]],
 
         [[-0.08329181,  0.01993457],
          [-1.1349709 , -0.01251321]],
 
         [[-0.07458224,  0.02177358],
          [-1.15353964, -0.01875158]],
 
         [[-0.1080673 ,  0.0237917 ],
          [-1.29698355, -0.00488533]],
 
         [[-0.08335042,  0.02313716],
          [-1.15772564, -0.0173916 ]],
 
         [[-0.06864991,  0.02315916],
          [-1.0786212 , -0.03810265]],
 
         [[-0.08550891,  0.02339963],
          [-1.14281173, -0.01406403]],
 
         [[-0.07384091,  0.02281805],
          [-1.

## Different time windows

In [5]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_individual_year',
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                        startyears = range(1965,2018),
                        windowlength = 1,
                                verbose = True)

[[-0.07492162  0.01840608]
 [-1.06941845 -0.02855685]]
Eigenvalues:[-0.05173924+0.13837045j -0.05173924-0.13837045j]
[[-0.10286279  0.01827781]
 [-1.12912815 -0.04507697]]
Eigenvalues:[-0.07396988+0.14072381j -0.07396988-0.14072381j]
Year 1965-1965, ensemble member slice(1, 97, None) finished
[-0.10286279  0.01827781 -1.12912815 -0.04507697]
----------------------------------------
[[ 0.0028347   0.05064465]
 [-1.65727807 -0.02291743]]
Eigenvalues:[-0.01004137+0.2894244j -0.01004137-0.2894244j]
[[-0.04547502  0.04703318]
 [-1.78968184 -0.17228116]]
Eigenvalues:[-0.10887809+0.28311566j -0.10887809-0.28311566j]
Year 1966-1966, ensemble member slice(1, 97, None) finished
[-0.04547502  0.04703318 -1.78968184 -0.17228116]
----------------------------------------
[[ 0.03525897  0.00909052]
 [-0.71763654 -0.05036247]]
Eigenvalues:[-0.00755175+0.06849039j -0.00755175-0.06849039j]
[[-0.0972718  -0.00879909]
 [-1.4631677  -0.17147175]]
Eigenvalues:[-0.0149944 +0.j -0.25374916+0.j]
Year 1967-1967

[[-0.12408475  0.01438877]
 [-1.99712249 -0.26017847]]
Eigenvalues:[-0.19213161+0.1552603j -0.19213161-0.1552603j]
Year 1989-1989, ensemble member slice(1, 97, None) finished
[-0.12408475  0.01438877 -1.99712249 -0.26017847]
----------------------------------------
[[-5.75041261e-02  2.11549928e-02]
 [-1.09939480e+00 -7.23969766e-04]]
Eigenvalues:[-0.02911405+0.14983889j -0.02911405-0.14983889j]
[[-0.15597999  0.02001804]
 [-1.34617613 -0.04530991]]
Eigenvalues:[-0.10064495+0.15455044j -0.10064495-0.15455044j]
Year 1990-1990, ensemble member slice(1, 97, None) finished
[-0.15597999  0.02001804 -1.34617613 -0.04530991]
----------------------------------------
[[ 0.08252103  0.02979662]
 [ 0.12392997 -0.010151  ]]
Eigenvalues:[ 0.11260308+0.j -0.04023305+0.j]
[[ 0.05550007  0.03137074]
 [ 0.32282947 -0.16579988]]
Eigenvalues:[ 0.09441886+0.j -0.20471867+0.j]
Year 1991-1991, ensemble member slice(1, 97, None) finished
[ 0.05550007  0.03137074  0.32282947 -0.16579988]
---------------------

[[-0.23704633  0.01589041]
 [-3.40482239 -0.19605624]]
Eigenvalues:[-0.21655128+0.23169806j -0.21655128-0.23169806j]
Year 2012-2012, ensemble member slice(1, 97, None) finished
[-0.23704633  0.01589041 -3.40482239 -0.19605624]
----------------------------------------
[[-0.14743953  0.02122894]
 [-1.50856484 -0.00365807]]
Eigenvalues:[-0.0755488+0.16388093j -0.0755488-0.16388093j]
[[-0.6749352   0.03341082]
 [-2.38606956 -0.04277753]]
Eigenvalues:[-0.50093127+0.j -0.21678146+0.j]
Year 2013-2013, ensemble member slice(1, 97, None) finished
[-0.6749352   0.03341082 -2.38606956 -0.04277753]
----------------------------------------
[[ 0.10818217  0.03375987]
 [-0.98876247 -0.07422173]]
Eigenvalues:[0.01698022+0.15831203j 0.01698022-0.15831203j]
[[-0.09064728 -0.01535239]
 [-2.33113178 -0.55533311]]
Eigenvalues:[-0.02337099+0.j -0.6226094 +0.j]
Year 2014-2014, ensemble member slice(1, 97, None) finished
[-0.09064728 -0.01535239 -2.33113178 -0.55533311]
---------------------------------------

(array([[[[-1.02862795e-01,  1.82778121e-02],
          [-1.12912815e+00, -4.50769664e-02]]],
 
 
        [[[-4.54750217e-02,  4.70331793e-02],
          [-1.78968184e+00, -1.72281162e-01]]],
 
 
        [[[-9.72718034e-02, -8.79909456e-03],
          [-1.46316770e+00, -1.71471751e-01]]],
 
 
        [[[-1.09393629e-01,  4.47056223e-03],
          [-8.91567786e-01, -1.72794388e-02]]],
 
 
        [[[-1.15839072e-01,  2.19808199e-02],
          [-1.84079779e+00, -1.65726607e-01]]],
 
 
        [[[-2.42700628e-01,  7.94252648e-02],
          [-2.22672878e-01, -2.01954461e-02]]],
 
 
        [[[-4.87816597e-02,  5.13158095e-03],
          [-1.60080294e+00, -2.64518161e-01]]],
 
 
        [[[-5.22588818e-02,  3.49109241e-02],
          [-1.08943768e+00,  1.67784041e-02]]],
 
 
        [[[-1.48571329e-01,  5.19702967e-02],
          [-1.77184845e+00,  7.15574054e-02]]],
 
 
        [[[-1.16456801e-01,  9.26570913e-03],
          [-1.80312522e+00, -1.01829644e-01]]],
 
 
        [[[ 1.358978

In [6]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_decade_all_ensemble', 
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                            startyears = range(1965,2010), #Anything iterable
                            windowlength = 10, #Inclusive
                            ensemble = [slice(1,97)], #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

CPU times: user 15 s, sys: 211 ms, total: 15.2 s
Wall time: 8.13 s


(array([[[[-4.80379341e-02,  2.08870577e-02],
          [-1.16338126e+00, -4.78995510e-02]]],
 
 
        [[[-3.75910704e-02,  2.02895805e-02],
          [-1.16405715e+00, -5.45999638e-02]]],
 
 
        [[[-4.19844187e-02,  1.95405433e-02],
          [-1.11300161e+00, -4.74536303e-02]]],
 
 
        [[[-5.52595090e-02,  2.21095372e-02],
          [-1.17109468e+00, -4.06513114e-02]]],
 
 
        [[[-5.62086435e-02,  2.56194939e-02],
          [-1.18394041e+00, -4.35930565e-02]]],
 
 
        [[[-5.56666893e-02,  2.60535061e-02],
          [-1.15343798e+00, -3.80140756e-02]]],
 
 
        [[[-5.25816741e-02,  2.48331550e-02],
          [-1.31084748e+00, -5.05865311e-02]]],
 
 
        [[[-6.37214205e-02,  2.63929121e-02],
          [-1.34457334e+00, -3.92883817e-02]]],
 
 
        [[[-6.06490248e-02,  2.59326269e-02],
          [-1.31077143e+00, -4.21205674e-02]]],
 
 
        [[[-5.76859027e-02,  2.25822742e-02],
          [-1.30978592e+00, -1.98500347e-02]]],
 
 
        [[[-6.805033

In [7]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_decade_each_ensemble', 
                        sst_index = indices.nino34_sst,
                        i20_index = indices.wholeP_i20,
                            startyears = range(1965,2010), #Anything iterable
                            windowlength = 10, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

CPU times: user 5min 9s, sys: 2.64 s, total: 5min 12s
Wall time: 2min 42s


(array([[[[-3.44864426e-02,  1.99173548e-02],
          [-1.17902109e+00, -3.91864347e-02]],
 
         [[-4.35692312e-02,  1.92513681e-02],
          [-9.63533372e-01, -5.12587255e-02]],
 
         [[-7.49525297e-02,  2.86654939e-02],
          [-1.50374716e+00,  6.51443209e-03]],
 
         ...,
 
         [[-6.85125763e-02,  1.86138689e-02],
          [-1.15253836e+00, -4.03656466e-02]],
 
         [[-3.16079318e-02,  2.13505718e-02],
          [-1.43733324e+00, -5.50329462e-02]],
 
         [[-4.78543362e-02,  1.42347767e-02],
          [-1.36286331e+00, -5.72357971e-02]]],
 
 
        [[[-2.03136176e-02,  1.89039896e-02],
          [-1.17689003e+00, -4.42149910e-02]],
 
         [[-4.51465898e-02,  1.98469177e-02],
          [-9.70466364e-01, -4.13084784e-02]],
 
         [[-6.97713842e-02,  3.12486853e-02],
          [-1.59513467e+00, -3.65447056e-03]],
 
         ...,
 
         [[-5.34469495e-02,  2.02158156e-02],
          [-1.14364269e+00, -5.65111411e-02]],
 
         [[-1.7

In [8]:
%%time

jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_3y_all_ensemble', 
                        sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = range(1965,2017), #Anything iterable
                            windowlength = 3, #Inclusive
                            ensemble = [slice(1,97)], #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

CPU times: user 7.82 s, sys: 96.4 ms, total: 7.92 s
Wall time: 4.15 s


(array([[[[-3.25471875e-02,  1.63678594e-02],
          [-1.30889939e+00, -8.17474901e-02]]],
 
 
        [[[-2.98972780e-02,  9.37501698e-03],
          [-1.42079657e+00, -9.28653320e-02]]],
 
 
        [[[-4.06277191e-02,  7.19609025e-03],
          [-1.33037902e+00, -9.62176589e-02]]],
 
 
        [[[-6.16099399e-02,  1.60997316e-02],
          [-6.25764030e-01, -4.49067085e-02]]],
 
 
        [[[-5.11302605e-02,  2.31542536e-02],
          [-7.84413116e-01, -1.07871136e-01]]],
 
 
        [[[-4.44791391e-02,  3.06698431e-02],
          [-7.86334527e-01, -1.81309112e-02]]],
 
 
        [[[-5.63084164e-02,  3.47704786e-02],
          [-1.26739183e+00, -7.16631421e-03]]],
 
 
        [[[-7.54826374e-02,  3.32295941e-02],
          [-1.41469454e+00,  7.33277360e-03]]],
 
 
        [[[-6.02777518e-02,  2.43705250e-02],
          [-1.49085045e+00, -3.83417050e-02]]],
 
 
        [[[-6.35867990e-02,  1.42477676e-02],
          [-1.43541705e+00, -7.38651005e-02]]],
 
 
        [[[-5.316603

In [9]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_sliding_5y_all_ensemble', 
                        sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = range(1965,2015), #Anything iterable
                            windowlength = 5, #Inclusive
                            ensemble = [slice(1,97)], #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-4.25490020e-02,  1.39964916e-02],
          [-1.38087603e+00, -8.03919088e-02]]],
 
 
        [[[-3.45950796e-02,  1.46276055e-02],
          [-9.66656778e-01, -7.00510493e-02]]],
 
 
        [[[-3.51063129e-02,  1.12611997e-02],
          [-8.57972614e-01, -6.68949479e-02]]],
 
 
        [[[-3.70044483e-02,  1.99210773e-02],
          [-8.73866952e-01, -4.18579216e-02]]],
 
 
        [[[-7.27345592e-02,  3.46141661e-02],
          [-1.08177469e+00, -2.74358142e-02]]],
 
 
        [[[-6.27251354e-02,  3.13734676e-02],
          [-1.11330544e+00, -9.44074294e-03]]],
 
 
        [[[-4.06495877e-02,  2.52505493e-02],
          [-1.28390406e+00, -3.81727115e-02]]],
 
 
        [[[-5.83774800e-02,  2.59861284e-02],
          [-1.33846502e+00, -2.36160131e-02]]],
 
 
        [[[-7.31025720e-02,  2.40936674e-02],
          [-1.48515952e+00, -4.10517880e-02]]],
 
 
        [[[-6.04305377e-02,  1.63751461e-02],
          [-1.47488918e+00, -7.45533579e-02]]],
 
 
        [[[-5.114779

In [10]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_1980_2000', 
                        sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = [1980], #Anything iterable
                            windowlength = 20, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-4.77807056e-02,  2.40850456e-02],
          [-1.00048839e+00, -1.50150116e-03]],
 
         [[-6.74691024e-02,  2.66984616e-02],
          [-1.05799384e+00, -7.69115763e-03]],
 
         [[-7.60579066e-02,  2.77049582e-02],
          [-1.17195855e+00, -2.01222078e-02]],
 
         [[-7.59712005e-02,  2.14887921e-02],
          [-1.29268991e+00, -1.68411911e-03]],
 
         [[-4.94146152e-02,  2.48569089e-02],
          [-1.02183833e+00, -2.50775009e-02]],
 
         [[-7.02213125e-02,  2.83818087e-02],
          [-9.85531576e-01, -6.93499556e-03]],
 
         [[-6.52052112e-02,  2.34007098e-02],
          [-1.12916045e+00, -1.06023786e-02]],
 
         [[-6.53219813e-02,  2.61162159e-02],
          [-1.02693008e+00, -3.73252604e-03]],
 
         [[-8.62914880e-02,  2.40940706e-02],
          [-1.20406646e+00, -5.82763144e-03]],
 
         [[-7.31911617e-02,  2.75310201e-02],
          [-1.00704031e+00, -8.75940008e-03]],
 
         [[-6.14322788e-02,  2.58037736e-02],
    

In [11]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_2000_2018', 
                        sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = [2000], #Anything iterable
                            windowlength = 19, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-1.17561651e-01,  2.37100153e-02],
          [-1.30542659e+00,  2.40022011e-02]],
 
         [[-1.44831367e-01,  2.70317178e-02],
          [-1.39585656e+00,  1.11464139e-02]],
 
         [[-1.33109994e-01,  2.59592301e-02],
          [-1.41644460e+00,  1.49266965e-03]],
 
         [[-1.49050941e-01,  2.55976598e-02],
          [-1.33816529e+00,  1.50527607e-02]],
 
         [[-1.42981808e-01,  2.60975941e-02],
          [-1.39824834e+00,  7.90090044e-03]],
 
         [[-1.38441959e-01,  2.52966090e-02],
          [-1.41631629e+00,  1.40954874e-02]],
 
         [[-1.49992531e-01,  2.36512404e-02],
          [-1.44699874e+00,  2.89863963e-02]],
 
         [[-1.58880988e-01,  2.49304814e-02],
          [-1.42707883e+00,  2.17103710e-02]],
 
         [[-1.65350559e-01,  2.82444621e-02],
          [-1.39852317e+00,  2.36986376e-02]],
 
         [[-1.29664352e-01,  2.28923979e-02],
          [-1.38529207e+00,  5.05404840e-03]],
 
         [[-1.29050586e-01,  2.27386568e-02],
    

In [12]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_1980_2002', 
                        sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = [1980], #Anything iterable
                            windowlength = 23, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-5.06882379e-02,  2.25798604e-02],
          [-9.70427556e-01,  5.29340324e-03]],
 
         [[-6.97285041e-02,  2.58248792e-02],
          [-1.04136959e+00,  3.64769130e-05]],
 
         [[-7.50827601e-02,  2.59737445e-02],
          [-1.13933297e+00, -1.66324514e-02]],
 
         [[-7.85198245e-02,  2.08719497e-02],
          [-1.25065467e+00,  3.62262800e-03]],
 
         [[-5.34232233e-02,  2.34880650e-02],
          [-1.02484670e+00, -2.17887509e-02]],
 
         [[-7.29855808e-02,  2.70755630e-02],
          [-9.87461723e-01, -4.07434993e-03]],
 
         [[-6.74229327e-02,  2.20268281e-02],
          [-1.10196587e+00, -4.21192395e-03]],
 
         [[-6.86814249e-02,  2.47082282e-02],
          [-1.01930919e+00, -1.87135107e-03]],
 
         [[-8.81312759e-02,  2.30454612e-02],
          [-1.12925690e+00,  3.04488702e-03]],
 
         [[-7.59756793e-02,  2.60974402e-02],
          [-9.93138097e-01, -5.82831739e-03]],
 
         [[-6.65849173e-02,  2.47484496e-02],
    

In [16]:
jcafe.fit_matrix_for_data_subset('fit_files/NINO3_SST__WHOLEPACIFIC_I20_1980_2002', 
                        sst_index = indices.nino3_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = [1980], #Anything iterable
                            windowlength = 23, #Inclusive
                            ensemble = range(97), #also has to be iterable
                            season = None, #None or one of 'DJF','MAM','SON','JJA'
                           )

(array([[[[-5.00915066e-02,  2.29620653e-02],
          [-9.47726375e-01, -1.02015398e-04]],
 
         [[-7.89497798e-02,  2.62060764e-02],
          [-1.01454832e+00, -7.12717362e-03]],
 
         [[-9.05887303e-02,  2.74466280e-02],
          [-1.12432878e+00, -2.12217776e-02]],
 
         [[-9.82910360e-02,  2.32260323e-02],
          [-1.22732411e+00, -2.77612729e-04]],
 
         [[-7.35704194e-02,  2.61357385e-02],
          [-1.06998870e+00, -1.84629644e-02]],
 
         [[-7.69119769e-02,  2.88332772e-02],
          [-9.64911883e-01, -9.32500563e-03]],
 
         [[-7.57217576e-02,  2.37735864e-02],
          [-1.11194312e+00, -9.11355693e-03]],
 
         [[-7.94970348e-02,  2.63633262e-02],
          [-1.00745918e+00, -6.72672284e-03]],
 
         [[-1.08727930e-01,  2.52924083e-02],
          [-1.14240755e+00,  4.06258316e-03]],
 
         [[-8.76552210e-02,  2.79003914e-02],
          [-9.74296009e-01, -7.61835124e-03]],
 
         [[-8.30111906e-02,  2.46554963e-02],
    

## Seasonal fits

In [13]:
%%time
for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_'+s, 
                            sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = np.array((1965,)), #Anything iterable
                            windowlength = 2019-1965, #That's a subtraction deliberately 
                            ensemble = range(97), #also has to be iterable
                            season = s,
                                     verbose = False,
                           )

CPU times: user 33.8 s, sys: 387 ms, total: 34.2 s
Wall time: 18.4 s


In [14]:
#Seasonal fits for each year
for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_yearly_'+s, 
                            sst_index = indices.nino34_sst,
                            i20_index = indices.wholeP_i20,
                                startyears = range(1965,2019), #Anything iterable
                                windowlength = 1,
                                ensemble = [slice(1,97)], #also has to be iterable
                                season = s,
                                     verbose = True,
                               )

[[-0.19579274  0.00902662]
 [-3.71625965 -0.00406637]]
Eigenvalues:[-0.09992956+0.15606251j -0.09992956-0.15606251j]
[[-0.21830329  0.00926493]
 [-3.23085361 -0.15761942]]
Eigenvalues:[-0.18796135+0.17033206j -0.18796135-0.17033206j]
Year 1965-1965, ensemble member slice(1, 97, None) finished
[-0.21830329  0.00926493 -3.23085361 -0.15761942]
----------------------------------------
[[-1.28550918e-01 -1.42802228e-03]
 [-1.50206374e+00 -8.09221736e-02]]
Eigenvalues:[-0.15681442+0.j -0.05265867+0.j]
[[-0.1970431  -0.01627749]
 [-2.12253381 -0.23749211]]
Eigenvalues:[-0.03029553+0.j -0.40423968+0.j]
Year 1966-1966, ensemble member slice(1, 97, None) finished
[-0.1970431  -0.01627749 -2.12253381 -0.23749211]
----------------------------------------
[[-0.11980509  0.0085061 ]
 [-1.59044208 -0.1046249 ]]
Eigenvalues:[-0.11221499+0.11606402j -0.11221499-0.11606402j]
[[-2.13776064e-01 -2.34814263e-03]
 [-2.74835842e+00 -2.48751992e-01]]
Eigenvalues:[-0.14904866+0.j -0.31347939+0.j]
Year 1967-19

[[-0.15558778  0.01360263]
 [-1.61015447 -0.00762157]]
Eigenvalues:[-0.08160467+0.12817503j -0.08160467-0.12817503j]
Year 1987-1987, ensemble member slice(1, 97, None) finished
[-0.15558778  0.01360263 -1.61015447 -0.00762157]
----------------------------------------
[[-1.04130907e-01 -1.51872222e-04]
 [-2.37509134e+00  4.77212500e-01]]
Eigenvalues:[-0.10475072+0.j  0.47783232+0.j]
[[-0.12272806  0.00837362]
 [-2.02243553  0.26994538]]
Eigenvalues:[-0.07340496+0.j  0.22062228+0.j]
Year 1988-1988, ensemble member slice(1, 97, None) finished
[-0.12272806  0.00837362 -2.02243553  0.26994538]
----------------------------------------
[[-0.02479418  0.03134585]
 [-1.55064912  0.05176276]]
Eigenvalues:[0.01348429+0.21712019j 0.01348429-0.21712019j]
[[-0.09279473  0.02506832]
 [-2.1476704  -0.02718917]]
Eigenvalues:[-0.05999195+0.22970083j -0.05999195-0.22970083j]
Year 1989-1989, ensemble member slice(1, 97, None) finished
[-0.09279473  0.02506832 -2.1476704  -0.02718917]
---------------------

[[-0.03765506  0.03989156]
 [-2.43975095  0.06792962]]
Eigenvalues:[0.01513728+0.30747103j 0.01513728-0.30747103j]
[[-0.04964362  0.03612724]
 [-2.61785478 -0.06183445]]
Eigenvalues:[-0.05573904+0.30747148j -0.05573904-0.30747148j]
Year 2009-2009, ensemble member slice(1, 97, None) finished
[-0.04964362  0.03612724 -2.61785478 -0.06183445]
----------------------------------------
[[-0.30499253  0.03124389]
 [-2.6359125   0.06737887]]
Eigenvalues:[-0.11880683+0.21838282j -0.11880683-0.21838282j]
[[-0.36019485  0.04353704]
 [-2.11704681 -0.05548924]]
Eigenvalues:[-0.20784205+0.26259966j -0.20784205-0.26259966j]
Year 2010-2010, ensemble member slice(1, 97, None) finished
[-0.36019485  0.04353704 -2.11704681 -0.05548924]
----------------------------------------
[[-0.61793447  0.06907043]
 [-6.65650532  0.80488939]]
Eigenvalues:[-0.12178806+0.j  0.30874298+0.j]
[[-0.63395432  0.06731429]
 [-4.913715    0.3923924 ]]
Eigenvalues:[-0.12078096+0.25964656j -0.12078096-0.25964656j]
Year 2011-2011

[[ 0.01107057  0.04611725]
 [-2.03254281 -0.05928976]]
Eigenvalues:[-0.02410959+0.30413424j -0.02410959-0.30413424j]
Year 1978-1978, ensemble member slice(1, 97, None) finished
[ 0.01107057  0.04611725 -2.03254281 -0.05928976]
----------------------------------------
[[-0.01353406  0.02845872]
 [-1.47778317 -0.23899602]]
Eigenvalues:[-0.12626504+0.17131123j -0.12626504-0.17131123j]
[[-0.09026212  0.02453242]
 [-2.16258193 -0.40335601]]
Eigenvalues:[-0.24680906+0.16895686j -0.24680906-0.16895686j]
Year 1979-1979, ensemble member slice(1, 97, None) finished
[-0.09026212  0.02453242 -2.16258193 -0.40335601]
----------------------------------------
[[ 1.06744045e-01  2.09865829e-02]
 [-1.77835713e+00  1.48737271e-03]]
Eigenvalues:[0.05411571+0.18588141j 0.05411571-0.18588141j]
[[-0.00480003  0.01286139]
 [-2.53157154 -0.15176424]]
Eigenvalues:[-0.07828213+0.16480265j -0.07828213-0.16480265j]
Year 1980-1980, ensemble member slice(1, 97, None) finished
[-0.00480003  0.01286139 -2.53157154 -0

[[-0.14321876  0.01499901]
 [-2.66308447  0.06076837]]
Eigenvalues:[-0.04122519+0.17187478j -0.04122519-0.17187478j]
Year 2001-2001, ensemble member slice(1, 97, None) finished
[-0.14321876  0.01499901 -2.66308447  0.06076837]
----------------------------------------
[[-0.05191085  0.02430942]
 [-1.17772449  0.09683421]]
Eigenvalues:[0.02246168+0.15198199j 0.02246168-0.15198199j]
[[-0.04120252  0.01898176]
 [-0.29936782 -0.16430315]]
Eigenvalues:[-0.10275283+0.04352112j -0.10275283-0.04352112j]
Year 2002-2002, ensemble member slice(1, 97, None) finished
[-0.04120252  0.01898176 -0.29936782 -0.16430315]
----------------------------------------
[[ 0.06924957  0.05571682]
 [-4.37978009 -0.04673497]]
Eigenvalues:[0.0112573+0.49057551j 0.0112573-0.49057551j]
[[-0.09626955  0.05395265]
 [-4.78633788 -0.05591659]]
Eigenvalues:[-0.07609307+0.50776818j -0.07609307-0.50776818j]
Year 2003-2003, ensemble member slice(1, 97, None) finished
[-0.09626955  0.05395265 -4.78633788 -0.05591659]
---------

[[ 0.09871054  0.0377554 ]
 [-0.36132635  0.03506994]]
Eigenvalues:[0.06689024+0.11238099j 0.06689024-0.11238099j]
[[-1.2497747   0.23754066]
 [ 0.24564567 -0.09237656]]
Eigenvalues:[-1.29816689+0.j -0.04398437+0.j]
Year 1970-1970, ensemble member slice(1, 97, None) finished
[-1.2497747   0.23754066  0.24564567 -0.09237656]
----------------------------------------
[[ 0.09719623  0.0196212 ]
 [-0.22709245 -0.12277928]]
Eigenvalues:[ 0.07462403+0.j -0.10020708+0.j]
[[-0.05778403  0.00246748]
 [-0.71670894 -0.1977269 ]]
Eigenvalues:[-0.07183112+0.j -0.18367982+0.j]
Year 1971-1971, ensemble member slice(1, 97, None) finished
[-0.05778403  0.00246748 -0.71670894 -0.1977269 ]
----------------------------------------
[[-0.05081045  0.04523119]
 [ 0.73846299 -0.11627596]]
Eigenvalues:[ 0.10212583+0.j -0.26921224+0.j]
[[-0.15867857  0.05696803]
 [ 1.12515884 -0.17644226]]
Eigenvalues:[ 0.08577133+0.j -0.42089216+0.j]
Year 1972-1972, ensemble member slice(1, 97, None) finished
[-0.15867857  0.05

[[-0.13752354  0.06756871]
 [-0.09712354  0.09508886]]
Eigenvalues:[-0.10467165+0.j  0.06223697+0.j]
[[-0.26191125  0.07068178]
 [ 0.07038087 -0.12443842]]
Eigenvalues:[-0.29166006+0.j -0.09468961+0.j]
Year 1994-1994, ensemble member slice(1, 97, None) finished
[-0.26191125  0.07068178  0.07038087 -0.12443842]
----------------------------------------
[[-0.17746456  0.05971009]
 [ 0.27458387 -0.34452872]]
Eigenvalues:[-0.10811422+0.j -0.41387907+0.j]
[[-0.32431356  0.05388428]
 [-0.07543774 -0.4371441 ]]
Eigenvalues:[-0.38072883+0.02970228j -0.38072883-0.02970228j]
Year 1995-1995, ensemble member slice(1, 97, None) finished
[-0.32431356  0.05388428 -0.07543774 -0.4371441 ]
----------------------------------------
[[-0.13828939  0.0151027 ]
 [-1.20793767  0.06279331]]
Eigenvalues:[-0.03774804+0.09019179j -0.03774804-0.09019179j]
[[-0.46708861  0.03729665]
 [-1.27052279  0.05265492]]
Eigenvalues:[-0.34915729+0.j -0.06527639+0.j]
Year 1996-1996, ensemble member slice(1, 97, None) finished


 [-0.20405716 -0.07864969]]
Eigenvalues:[ 0.04959504+0.j -0.07465946+0.j]
[[-0.02264691 -0.01123125]
 [-0.77678986 -0.19954799]]
Eigenvalues:[ 0.01754089+0.j -0.23973579+0.j]
Year 1967-1967, ensemble member slice(1, 97, None) finished
[-0.02264691 -0.01123125 -0.77678986 -0.19954799]
----------------------------------------
[[ 0.01681338  0.00150018]
 [-0.36704682 -0.01748408]]
Eigenvalues:[-0.00033535+0.01601736j -0.00033535-0.01601736j]
[[-1.03054338e-01 -4.96742619e-04]
 [-5.87621191e-01 -2.83836019e-02]]
Eigenvalues:[-0.10677778+0.j -0.02466016+0.j]
Year 1968-1968, ensemble member slice(1, 97, None) finished
[-1.03054338e-01 -4.96742619e-04 -5.87621191e-01 -2.83836019e-02]
----------------------------------------
[[ 0.02373946  0.00920512]
 [-0.3243599   0.05246126]]
Eigenvalues:[0.03810036+0.05272131j 0.03810036-0.05272131j]
[[-0.04981688  0.00294154]
 [-0.44716767 -0.07576796]]
Eigenvalues:[-0.06279242+0.03386736j -0.06279242-0.03386736j]
Year 1969-1969, ensemble member slice(1, 

[[ 0.23177173 -0.01520692]
 [ 0.62947898 -0.20891383]]
Eigenvalues:[ 0.20885869+0.j -0.1860008 +0.j]
[[ 0.00748947 -0.01554926]
 [-0.07154222 -0.21747642]]
Eigenvalues:[ 0.01233019+0.j -0.22231713+0.j]
Year 1992-1992, ensemble member slice(1, 97, None) finished
[ 0.00748947 -0.01554926 -0.07154222 -0.21747642]
----------------------------------------
[[ 0.12329863 -0.0138357 ]
 [ 0.04526241 -0.06900379]]
Eigenvalues:[ 0.11998501+0.j -0.06569017+0.j]
[[ 0.09889087 -0.02749664]
 [-0.04814212 -0.24927678]]
Eigenvalues:[ 0.10265227+0.j -0.25303818+0.j]
Year 1993-1993, ensemble member slice(1, 97, None) finished
[ 0.09889087 -0.02749664 -0.04814212 -0.24927678]
----------------------------------------
[[ 0.10052158  0.02733042]
 [-0.27595665  0.16676439]]
Eigenvalues:[0.13364298+0.08028066j 0.13364298-0.08028066j]
[[ 0.09642279  0.02132858]
 [ 0.60384637 -0.15144001]]
Eigenvalues:[ 0.14053358+0.j -0.1955508 +0.j]
Year 1994-1994, ensemble member slice(1, 97, None) finished
[ 0.09642279  0.02

[[ 0.03410915 -0.06409829]
 [-0.53017322 -0.31454806]]
Eigenvalues:[ 0.11350019+0.j -0.39393909+0.j]
Year 2015-2015, ensemble member slice(1, 97, None) finished
[ 0.03410915 -0.06409829 -0.53017322 -0.31454806]
----------------------------------------
[[-0.49714189  0.02895375]
 [-3.82280195  0.11783875]]
Eigenvalues:[-0.18965157+0.12702027j -0.18965157-0.12702027j]
[[-2.2162434   0.11991695]
 [-7.1927665   0.29525733]]
Eigenvalues:[-1.80569974+0.j -0.11528633+0.j]
Year 2016-2016, ensemble member slice(1, 97, None) finished
[-2.2162434   0.11991695 -7.1927665   0.29525733]
----------------------------------------
[[-0.07015368  0.00770903]
 [-0.62151522  0.04015247]]
Eigenvalues:[-0.0150006+0.04182604j -0.0150006-0.04182604j]
[[-5.01166879  0.25815264]
 [ 4.55718076 -0.22975915]]
Eigenvalues:[-5.24618786e+00+0.j  4.75992883e-03+0.j]
Year 2017-2017, ensemble member slice(1, 97, None) finished
[-5.01166879  0.25815264  4.55718076 -0.22975915]
----------------------------------------
[[-0

In [15]:

for s in ('DJF','MAM','JJA','SON'):
    jcafe.fit_matrix_for_data_subset('fit_files/NINO34_SST__WHOLEPACIFIC_I20_10y_'+s, 
                            sst_index = indices.nino34_sst,
                                 i20_index = indices.wholeP_i20,
                            startyears = range(1965,2010), #Anything iterable
                            windowlength = 10, 
                            ensemble =  range(97), #also has to be iterable
                            season = s,
                           )